test.task ("postgresql.tasks.Query")
    .useMockPgClient ()
    .should ("output each row for the select query")
        .given ("SELECT * FROM @1 WHERE id = &2", "users", 1)
        .registerDbService ()
        .before (s => s.db.client.result = ({ command: "SELECT", rows: [{ id: 3 }, { id: 4 }] }))
        .returns ([{ id: 3 }, { id: 4 }])
        .expectingPropertyToBe ("db.client.statement", `SELECT * FROM "users" WHERE id = '1'`)
        .commit ()

    .should ("output the number of affected rows for other type of queries")
        .given ("UPDATE @1 SET name = &2 WHERE id = &3", "users", "John", 1)
        .registerDbService ()
        .before (s => s.db.client.result = ({ command: "UPDATE", rowCount: 1 }))
        .returns ("UPDATE 1")
        .expectingPropertyToBe ("db.client.statement", `UPDATE "users" SET name = 'John' WHERE id = '1'`)
        .commit ()
;
