test.task ("postgresql.tasks.Query")
    .useMockPgClient ()
    .should ("output each row for the select query")
        .given ("SELECT * FROM @1 WHERE id = &2", "users", 1)
        .before (s => s.context = nit.Task.Context.new ({ "postgresql.Task.db": s.db }))
        .before (s => s.db.client.result = ({ command: "SELECT", rows: [{ id: 3 }, { id: 4 }] }))
        .mock (nit, "inspect")
        .expectingPropertyToBe ("db.client.statement", `SELECT * FROM "users" WHERE id = '1'`)
        .expectingPropertyToBe ("mocks.0.invocations.0.args.0", { id: 3 })
        .expectingPropertyToBe ("mocks.0.invocations.1.args.0", { id: 4 })
        .commit ()

    .should ("output the number of affected rows for other type of queries")
        .given ("UPDATE @1 SET name = &2 WHERE id = &3", "users", "John", 1)
        .before (s => s.context = nit.Task.Context.new ({ "postgresql.Task.db": s.db }))
        .before (s => s.db.client.result = ({ command: "UPDATE", rowCount: 1 }))
        .mock (nit, "inspect")
        .expectingPropertyToBe ("db.client.statement", `UPDATE "users" SET name = 'John' WHERE id = '1'`)
        .expectingPropertyToBe ("mocks.0.invocations.0.args.0", "UPDATE")
        .expectingPropertyToBe ("mocks.0.invocations.0.args.1", 1)
        .commit ()
;
