test.method ("postgresql.Command", "run")
    .should ("disconnect the created database")
        .up (s => s.class = s.class.defineSubclass ("MyCmd")
            .onRun (ctx => s.db = ctx.db)
        )
        .before (s => s.context = s.class.Context.new ({ command: s.object, input: { database: "testdb" } }))
        .before (s => s.args = s.context)
        .mock ("postgresql.Database.prototype", "disconnect")
        .expectingPropertyToBe ("mocks.0.invocations.length", 1)
        .expectingPropertyToBe ("db.database", "testdb")
        .commit ()

    .should ("not register the service provider if one already exists")
        .up (s => s.class = s.class.defineSubclass ("MyCmd")
            .onRun (ctx => s.db = ctx.db)
        )
        .before (s => s.context = s.class.Context.new ({ command: s.object }))
        .before (s => s.context.serviceproviders.push (nit.new ("postgresql.serviceproviders.Database")))
        .before (s => s.args = s.context)
        .mock ("postgresql.Database.prototype", "disconnect")
        .expectingPropertyToBe ("mocks.0.invocations.length", 1)
        .commit ()
;
